PongChat/PongChat/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path("pingpong/", include("pingpong.urls")),
    path("", include("accounts.urls")),
    path("chat/", include("chat.urls")),
    path("prometheus/", include("django_prometheus.urls")),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PongChat/accounts/urls.py
from django.urls import path

from . import views
from .views import switch_language

app_name = "accounts"

urlpatterns = [
    path("", views.TopView.as_view(), name="top"),
    path("login", views.Login.as_view(), name="login"),
    path("logout", views.Logout.as_view(), name="logout"),
    path("my_page/<int:pk>/", views.MyPage.as_view(), name="my_page"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signup_done/", views.SignupDone.as_view(), name="signup_done"),
    path(
        "username_update/<int:pk>",
        views.UsernameUpdate.as_view(),
        name="username_update",
    ),
    path("password_change/", views.PasswordChange.as_view(), name="password_change"),
    path(
        "password_change_done/",
        views.PasswordChangeDone.as_view(),
        name="password_change_done",
    ),
    path(
        "profile_image_update/<int:pk>",
        views.ProfileImageUpdate.as_view(),
        name="profile_image_update",
    ),
    path("switch-language/<str:language>/", switch_language, name="switch_language"),
]

PongChat/chat/urls.py
from django.urls import path

from .views import (
    chat_view,
    get_or_create_chatroom,
    profile_view,
    user_block_post,
    user_friend_post,
    user_list,
)

urlpatterns = [
    path("", user_list, name="chat-home"),
    path("<username>", get_or_create_chatroom, name="start-chat"),
    path("room/<chatroom_name>", chat_view, name="chatroom"),
    path("@<username>/", profile_view, name="profile"),
    path("block/<str:username>", user_block_post, name="block"),
    path("friend/<str:username>", user_friend_post, name="friend"),
]

PongChat/pingpong/urls.py
from django.urls import path

from . import views

app_name = "pingpong"

urlpatterns = [
    path("", views.index, name="index"),
    path("game_play", views.game_play, name="game_play"),
    path("home", views.home, name="home"),
    path("how_to_play", views.how_to_play, name="how_to_play"),
    path("multiplayer_lobby", views.multiplayer_lobby, name="multiplayer_lobby"),
    path("multiplayer_options", views.multiplayer_options, name="multiplayer_options"),
    path(
        "multiplayer_play_four",
        views.multiplayer_play_four,
        name="multiplayer_play_four",
    ),
    path(
        "multiplayer_play_local",
        views.multiplayer_play_local,
        name="multiplayer_play_local",
    ),
    path(
        "multiplayer_play_remote/<str:game_id>",
        views.multiplayer_play_remote,
        name="multiplayer_play_remote",
    ),
    path("single_play_setup", views.single_play_setup, name="single_play_setup"),
    path("single_play_start", views.single_play_start, name="single_play_start"),
    path("tournament_bracket", views.tournament_bracket, name="tournament_bracket"),
    path("tournament_finish", views.tournament_finish, name="tournament_finish"),
    path("tournament_play", views.tournament_play, name="tournament_play"),
    path(
        "tournament_registration",
        views.tournament_registration,
        name="tournament_registration",
    ),
    path(
        "tournament_winner_name_response/<int:round>",
        views.tournament_winner_name_response,
        name="tournament_winner_name_response",
    ),
]

PongChat/templates/common/base.html
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Pong Chat{% endblock title %}</title>
    {% load static %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/common.css' %}" />
    <link
      rel="icon"
      href="{% static 'images/profile_sample.png' %}"
      type="image/x-icon"
    />
  </head>
  <body>
    {% include 'common/header.html' %}
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2">{% include 'common/sidebar.html' %}</div>
        <main
          class="col-md-9 col-lg-9 py-3 main-content"
          id="content-placeholder"
        >
          {% block content %}{% endblock content %}
        </main>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'scripts/scripts.js' %}"></script>
  </body>
</html>

PongChat/templates/common/header.html
{% load static %}
{% load i18n %}
<nav class="navbar navbar-light bg-light p-3 fixed-top shadow-sm">
  <button
    class="navbar-toggler d-md-none collapsed"
    type="button"
    data-bs-toggle="offcanvas"
    data-bs-target="#offcanvasSidebar"
    aria-controls="offcanvasSidebar"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{% url 'accounts:top' %}"> Pong Chat </a>
  <div class="d-flex">
    <!-- 言語切り替えドロップダウン -->
    <div class="dropdown me-2">
      <button
        class="btn btn-outline-secondary dropdown-toggle"
        type="button"
        id="languageDropdown"
        data-bs-toggle="dropdown"
        aria-expanded="false"
      >
          <i class="bi bi-type"></i>
      </button>
      <ul class="dropdown-menu" aria-labelledby="languageDropdown">
        <li><a class="dropdown-item async-link" href="{% url 'accounts:switch_language' 'ja' %}">日本語</a></li>
        <li><a class="dropdown-item async-link" href="{% url 'accounts:switch_language' 'en' %}">English</a></li>
        <li><a class="dropdown-item async-link" href="{% url 'accounts:switch_language' 'fr' %}">Français</a></li>
      </ul>
    </div>
    <!-- ユーザードロップダウン -->
    <div class="dropdown">
      <button
        class="btn dropdown-toggle"
        type="button"
        id="dropdownMenuButton"
        data-bs-toggle="dropdown"
        aria-expanded="false"
        data-bs-auto-close="outside"
      >
        {% if not user.is_authenticated %}
        <i class="bi bi-person-circle"></i>
        {% trans "ゲスト" %}
        {% else %}
        <img
          src="{% if user.profile_image %}{{ user.profile_image.url }}{% else %}{% static 'images/profile_sample.png' %}{% endif %}"
          alt="Profile Picture"
          class="profile-pic"
        />
        {% endif %}
      </button>
      <ul
        class="dropdown-menu dropdown-menu-end"
        aria-labelledby="dropdownMenuButton"
      >
        {% if not user.is_authenticated %}
        <li>
          <a class="dropdown-item" href="{% url 'accounts:login' %}">{% trans "ログイン" %}</a>
        </li>
        <li>
          <a class="dropdown-item async-link" href="{% url 'accounts:signup' %}"
          >{% trans "サインアップ" %}</a
          >
        </li>
        {% else %}
        <p class="dropdown-item-text">{{ user.username }}</p>
        <li><hr class="dropdown-divider" /></li>
        <li>
          <a class="dropdown-item" href="{% url 'accounts:my_page' user.pk %}"
          >{% trans "マイページ" %}</a
          >
        </li>
        <form action="{% url 'accounts:logout' %}" method="post">
          {% csrf_token %}
          <button type="submit" class="dropdown-item">{% trans "ログアウト" %}</button>
        </form>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

PongChat/templates/common/sidebar.html
<nav id="sidebar" class="bg-light sidebar">
  <div class="position-sticky">
    <ul class="nav flex-column">
      {% include 'common/sidebar_link.html' %}
    </ul>
  </div>
</nav>
<div
  class="offcanvas offcanvas-start"
  tabindex="-1"
  id="offcanvasSidebar"
  aria-labelledby="offcanvasSidebarLabel"
>
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasSidebarLabel">Pong Chat</h5>
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="offcanvas"
      aria-label="Close"
    ></button>
  </div>
  <div class="offcanvas-body">
    <ul class="nav flex-column">
      {% include 'common/sidebar_link.html' %}
    </ul>
  </div>
</div>

PongChat/templates/common/sidebar_link.html
{% load i18n %}
<li class="nav-item mb-1">
  <a class="nav-link" aria-current="page" href="{% url 'accounts:top' %}">
    <i class="bi bi-house-door"></i>
    <span class="ml-2">{% trans "ホーム" %}</span>
  </a>
</li>

<li class="nav-item mb-1">
  <a class="nav-link" href="{% url 'chat-home' %}">
    <i class="bi bi-chat-dots"></i>
    <span class="ml-2">{% trans "チャット" %}</span>
  </a>
</li>

<li class="nav-item mb-1">
  <a class="nav-link" href="{% url 'pingpong:index' %}">
    <i class="bi bi-controller"></i>
    <span class="ml-2">{% trans "ゲーム" %}</span>
  </a>
</li>