PongChat/PongChat/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path("pingpong/", include("pingpong.urls")),
    path("", include("accounts.urls")),
    path("chat/", include("chat.urls")),
    path("prometheus/", include("django_prometheus.urls")),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PongChat/accounts/urls.py
from django.urls import path

from . import views
from .views import switch_language

app_name = "accounts"

urlpatterns = [
    path("", views.TopView.as_view(), name="top"),
    path("login", views.Login.as_view(), name="login"),
    path("logout", views.Logout.as_view(), name="logout"),
    path("my_page/<int:pk>/", views.MyPage.as_view(), name="my_page"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signup_done/", views.SignupDone.as_view(), name="signup_done"),
    path(
        "username_update/<int:pk>",
        views.UsernameUpdate.as_view(),
        name="username_update",
    ),
    path("password_change/", views.PasswordChange.as_view(), name="password_change"),
    path(
        "password_change_done/",
        views.PasswordChangeDone.as_view(),
        name="password_change_done",
    ),
    path(
        "profile_image_update/<int:pk>",
        views.ProfileImageUpdate.as_view(),
        name="profile_image_update",
    ),
    path("switch-language/<str:language>/", switch_language, name="switch_language"),
]

PongChat/chat/urls.py
from django.urls import path

from .views import (
    chat_view,
    get_or_create_chatroom,
    profile_view,
    user_block_post,
    user_friend_post,
    user_list,
)

urlpatterns = [
    path("", user_list, name="chat-home"),
    path("<username>", get_or_create_chatroom, name="start-chat"),
    path("room/<chatroom_name>", chat_view, name="chatroom"),
    path("@<username>/", profile_view, name="profile"),
    path("block/<str:username>", user_block_post, name="block"),
    path("friend/<str:username>", user_friend_post, name="friend"),
]

PongChat/pingpong/urls.py
from django.urls import path

from . import views

app_name = "pingpong"

urlpatterns = [
    path("", views.index, name="index"),
    path("game_play", views.game_play, name="game_play"),
    path("home", views.home, name="home"),
    path("how_to_play", views.how_to_play, name="how_to_play"),
    path("multiplayer_lobby", views.multiplayer_lobby, name="multiplayer_lobby"),
    path("multiplayer_options", views.multiplayer_options, name="multiplayer_options"),
    path(
        "multiplayer_play_four",
        views.multiplayer_play_four,
        name="multiplayer_play_four",
    ),
    path(
        "multiplayer_play_local",
        views.multiplayer_play_local,
        name="multiplayer_play_local",
    ),
    path(
        "multiplayer_play_remote/<str:game_id>",
        views.multiplayer_play_remote,
        name="multiplayer_play_remote",
    ),
    path("single_play_setup", views.single_play_setup, name="single_play_setup"),
    path("single_play_start", views.single_play_start, name="single_play_start"),
    path("tournament_bracket", views.tournament_bracket, name="tournament_bracket"),
    path("tournament_finish", views.tournament_finish, name="tournament_finish"),
    path("tournament_play", views.tournament_play, name="tournament_play"),
    path(
        "tournament_registration",
        views.tournament_registration,
        name="tournament_registration",
    ),
    path(
        "tournament_winner_name_response/<int:round>",
        views.tournament_winner_name_response,
        name="tournament_winner_name_response",
    ),
]

PongChat/accounts/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
    UserCreationForm,
)
from django.utils.translation import gettext_lazy

from .models import CustomUser
from .widgets import CustomClearableFileInput


class LoginForm(AuthenticationForm):
    """Form for user login.

    This form is used for authenticating users. It customizes the
    appearance of the form fields by adding Bootstrap classes and
    placeholders.

    Args:
        AuthenticationForm (class): Inherits from Django's AuthenticationForm.

    Attributes:
        fields (dict): The form fields for username and password.
    """

    def __init__(self, *args, **kwargs):
        """Initializes the form.

        Customizes each form field to include Bootstrap CSS classes and
        placeholders derived from the field labels.

        Args:
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.
        """
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"
            field.widget.attrs["placeholder"] = field.label


class CustomUserCreationForm(UserCreationForm):
    """Form for creating a new user.

    This form is used for registering new users. It includes fields for
    username, password, and profile image. It customizes the appearance
    of the form fields by adding Bootstrap classes and setting labels.

    Args:
        UserCreationForm (class): Inherits from Django's UserCreationForm.

    Attributes:
        Meta (class): Meta class to specify the model and fields used in the form.
        fields (dict): The form fields for username, password, and profile image.
    """

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ("username", "password1", "password2", "profile_image")

    def __init__(self, *args, **kwargs):
        """Initializes the form.

        Customizes each form field to include Bootstrap CSS classes.
        Sets a custom label for the profile image field.

        Args:
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.
        """
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            field = self.fields[field_name]
            field.widget.attrs["class"] = "form-control"
            if field_name == "profile_image":
                field.label = gettext_lazy("プロフィール画像")


class UsernameUpdateForm(forms.ModelForm):
    """Form for updating the username.

    This form allows users to update their username.

    Attributes:
        model (Model): The model associated with this form.
        fields (tuple): The fields to be included in the form.
    """

    class Meta:
        model = CustomUser
        fields = ("username",)

    def __init__(self, *args, **kwargs):
        """Initializes the form with Bootstrap CSS classes.

        Args:
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.
        """
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


class CustomPasswordChangeForm(PasswordChangeForm):
    """Form for changing the user's password.

    This form allows users to change their password.

    Attributes:
        model (Model): The model associated with this form.
        fields (tuple): The fields to be included in the form.
    """

    def __init__(self, *args, **kwargs):
        """Initializes the form with Bootstrap CSS classes.

        Args:
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.
        """
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


class ProfileImageUpdateForm(forms.ModelForm):
    """Form for updating the profile image.

    This form allows users to update their profile image.

    Attributes:
        model (Model): The model associated with this form.
        fields (tuple): The fields to be included in the form.
        widgets (dict): Custom widgets for the form fields.
    """

    class Meta:
        model = CustomUser
        fields = ("profile_image",)
        widgets = {"profile_image": CustomClearableFileInput}

    def __init__(self, *args, **kwargs):
        """Initializes the form with Bootstrap CSS classes and custom labels.

        Args:
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.
        """
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.label = "プロフィール画像"
            field.widget.attrs["class"] = "form-control"
            field.widget.attrs["required"] = ""

PongChat/accounts/views.py
from django.conf import settings
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
)
from django.shortcuts import redirect, render, resolve_url
from django.urls import reverse_lazy
from django.utils import translation
from django.views import View, generic

from .forms import (
    CustomPasswordChangeForm,
    CustomUserCreationForm,
    LoginForm,
    ProfileImageUpdateForm,
    UsernameUpdateForm,
)
from .models import CustomUser


class TopView(generic.TemplateView):
    """View for the top page.

    This view renders the top page template.

    Attributes:
        template_name (str): The template to be used for the top page.
    """

    template_name = "accounts/top.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            user = CustomUser.objects.get(pk=request.user.pk)
            translation.activate(user.default_language)
        return super().get(request, *args, **kwargs)


class Login(LoginView):
    """View for the login page.

    This view handles user login.

    Attributes:
        form_class (Form): The form used for login.
        template_name (str): The template to be used for the login page.
    """

    form_class = LoginForm
    template_name = "accounts/login.html"


class Logout(LogoutView):
    """View for the logout page.

    This view handles user logout and renders the logout completion page.

    Attributes:
        template_name (str): The template to be used for the logout completion page.
    """

    template_name = "accounts/logout_done.html"


class OnlyYouMixin(UserPassesTestMixin):
    """Mixin that allows access only to the user with the matching primary key.

    This mixin ensures that the view can only be accessed by the user
    whose primary key matches the 'pk' URL parameter.

    Attributes:
        raise_exception (bool): Whether to raise an exception if the test fails.
    """

    raise_exception = True

    def test_func(self):
        """Test if the current user matches the 'pk' URL parameter.

        Returns:
            bool: True if the current user's primary key matches
            the 'pk' parameter, False otherwise.
        """
        user = self.request.user
        return user.pk == self.kwargs["pk"]


class MyPage(OnlyYouMixin, generic.DetailView):
    """View for the user's personal page.

    This view displays the personal page of the user whose primary key
    matches the 'pk' URL parameter. Access is restricted to the user
    themselves.

    Attributes:
        model (Model): The model to be used for the detail view.
        template_name (str): The template to be used for the personal page.
    """

    model = CustomUser
    template_name = "accounts/my_page.html"

    def get_context_data(self, **kwargs):
        """Adds extra context data to the view.

        Args:
            **kwargs: Arbitrary keyword arguments.

        Returns:
            dict: The context data.
        """
        context = super().get_context_data(**kwargs)
        context["friends"] = self.object.friend_users.all()
        return context


class SignUpView(View):
    """View for the user sign-up page.

    This view handles the user registration process.

    Attributes:
        form_class (Form): The form used for user registration.
        template_name (str): The template to be used for the registration page.
    """

    form_class = CustomUserCreationForm
    template_name = "accounts/user_form.html"

    def get(self, request):
        """Handles GET requests and displays the registration form.

        Args:
            request (HttpRequest): The HTTP request object.

        Returns:
            HttpResponse: The rendered registration form page.
        """
        form = self.form_class()
        context = {"form": form, "process_name": "Sign Up"}
        return render(request, self.template_name, context)

    def post(self, request):
        """Handles POST requests and processes the registration form.

        Args:
            request (HttpRequest): The HTTP request object.

        Returns:
            HttpResponse: Redirects to the sign-up done page if the form is valid,
                          otherwise re-renders the registration form with errors.
        """
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy("accounts:signup_done"))
        else:
            context = {"form": form, "process_name": "Sign Up"}
            return render(request, "accounts/user_form.html", context)


class SignupDone(generic.TemplateView):
    """View for the sign-up completion page.

    This view renders the template that confirms the user has successfully signed up.

    Attributes:
        template_name (str): The template to be used for the sign-up completion page.
    """

    template_name = "accounts/signup_done.html"


class UsernameUpdate(OnlyYouMixin, generic.UpdateView):
    """View for updating the username.

    This view allows users to update their username.

    Attributes:
        model (Model): The model associated with this view.
        form_class (Form): The form used for updating the username.
        template_name (str): The template used for rendering the view.
    """

    model = CustomUser
    form_class = UsernameUpdateForm
    template_name = "accounts/user_form.html"

    def get_success_url(self):
        """Returns the URL to redirect to after successful form submission.

        Returns:
            str: The URL to redirect to.
        """
        return resolve_url("accounts:my_page", pk=self.kwargs["pk"])

    def get_context_data(self, **kwargs):
        """Adds extra context data to the view.

        Args:
            **kwargs: Arbitrary keyword arguments.

        Returns:
            dict: The context data.
        """
        context = super().get_context_data(**kwargs)
        context["process_name"] = "Update Username"
        return context


class ProfileImageUpdate(OnlyYouMixin, generic.UpdateView):
    """View for updating the profile image.

    This view allows users to update their profile image.

    Attributes:
        model (Model): The model associated with this view.
        form_class (Form): The form used for updating the profile image.
        template_name (str): The template used for rendering the view.
    """

    model = CustomUser
    form_class = ProfileImageUpdateForm
    template_name = "accounts/user_form.html"

    def get_success_url(self):
        """Returns the URL to redirect to after successful form submission.

        Returns:
            str: The URL to redirect to.
        """
        return resolve_url("accounts:my_page", pk=self.kwargs["pk"])

    def get_context_data(self, **kwargs):
        """Adds extra context data to the view.

        Args:
            **kwargs: Arbitrary keyword arguments.

        Returns:
            dict: The context data.
        """
        context = super().get_context_data(**kwargs)
        context["process_name"] = "Update Profile Image"
        return context


class PasswordChange(PasswordChangeView):
    """View for changing the password.

    This view allows users to change their password.

    Attributes:
        form_class (Form): The form used for changing the password.
        success_url (str): The URL to redirect to after successful password change.
        template_name (str): The template used for rendering the view.
    """

    form_class = CustomPasswordChangeForm
    success_url = reverse_lazy("accounts:password_change_done")
    template_name = "accounts/user_form.html"

    def get_context_data(self, **kwargs):
        """Adds extra context data to the view.

        Args:
            **kwargs: Arbitrary keyword arguments.

        Returns:
            dict: The context data.
        """
        context = super().get_context_data(**kwargs)
        context["process_name"] = "Change Password"
        return context


class PasswordChangeDone(PasswordChangeDoneView):
    """View for password change confirmation.

    This view confirms that the user's password has been successfully changed.

    Attributes:
        template_name (str): The template used for rendering the view.
    """

    template_name = "accounts/password_change_done.html"


def switch_language(request, language):
    translation.activate(language)
    request.session[settings.LANGUAGE_SESSION_KEY] = language

    if request.user.is_authenticated:
        user = CustomUser.objects.get(pk=request.user.pk)
        user.default_language = language
        user.save()

    referer = request.META.get("HTTP_REFERER")

    if referer:
        if language == "ja":
            return redirect("accounts:top")
        return redirect(f"/{language}")
    return redirect("accounts:top")

PongChat/accounts/templates/accounts/login.html
{% extends 'common/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
{% load i18n %}
<div class="container">
  <div class="col-md-6 offset-md-3">
    <div class="card mt-3 mb-3 bg-light">
      <div class="card-header bg-primary text-light">
        <h4>Log in</h4>
      </div>
      <div class="card-body">
        <form action="" method="POST">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group p-2">
            {{ field.label_tag }}
            {{ field }}
            {% if field.errors %}
            <div class="alert alert-danger mt-2" role="alert">
              {% for error in field.errors %}
              <div>{{ error }}</div>
              {% endfor %}
            </div>
            {% endif %}
          </div>
          {% endfor %}
          {% if form.non_field_errors %}
          <div class="alert alert-danger" role="alert">
              {{ form.non_field_errors }}
          </div>
          {% endif %}
          <div class="row text-center">
            <div class="col-md-6 mb-2">
              <button type="submit" class="btn btn-primary btn-lg btn-block shadow-sm">{% trans "ログイン" %}</button>
            </div>
            <div class="col-md-6">
              <button type="button" class="btn btn-secondary btn-lg btn-block shadow-sm" onclick="location.href='{% url 'accounts:signup' %}'">{% trans "サインアップ" %}</button>
            </right-click-form>
            <input type="hidden" name="next" value="{{ next }}" />
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

PongChat/accounts/templates/accounts/logout_done.html
{% extends "common/base.html" %}
{% block title%}Logout Done{% endblock %}
{% block content %}
{% load i18n %}
<div class="container">
  <div class="col-md-6 offset-md-3">
    <div class="card mt-3 mb-3 bg-light">
      <div class="card-header bg-primary text-light">
        <h4>Log out</h4>
      </div>
      <div class="card-body">
        <p>{% trans "ログアウトしました" %}</p>
        <hr class="mt-2 mb-2" />
        <p>
          <a href="{% url 'accounts:login' %}" class="logout"
            >{% trans "もう一度ログインする" %}</a
          >
        </p>
        <p>
          <a href="{% url 'accounts:top' %}" class="logout"
            >{% trans "トップページに戻る" %}</a
          >
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

PongChat/accounts/templates/accounts/my_page.html
{% extends 'common/base.html' %}
{% block title %}マイページ{% endblock %}
{% block content %}
{% load i18n %}
<div class="container">
  <div class="d-flex align-items-center mt-1">
    <img
      src="{{ user.profile_image.url }}"
      alt="Profile Image"
      class="rounded-circle border"
      style="width: 50px; height: 50px; object-fit: cover"
    />
    <h2 class="ml-3">{{ user.username }}</h2>
  </div>
  <hr />

  <!-- アカウント情報 -->
  <div class="row">
    <div class="col d-flex align-items-center">
      <h3 class="mr-2">{% trans "登録情報" %}</h3>
      <a href="{% url 'accounts:username_update' user.pk %}"
        ><i class="bi bi-pencil-square"></i
      ></a>
    </div>
  </div>
  <table class="table table-bordered">
    <tbody>
      <tr>
        <td style="width: 50%">{% trans "ユーザー名" %}</td>
        <td style="width: 50%">{{ user.username }}</td>
      </tr>
    </tbody>
  </table>

  <!-- プロフィール画像 -->
  <div class="row mb-4">
    <div class="col">
      <div class="d-flex align-items-center">
        <h3 class="mr-2">{% trans "プロフィール画像" %}</h3>
        <a href="{% url 'accounts:profile_image_update' user.pk %}" class="async-link"
          ><i class="bi bi-pencil-square"></i
        ></a>
      </div>
      {% if user.profile_image %}
      <img
        src="{{ user.profile_image.url }}"
        alt="Profile Image"
        class="rounded-circle border"
        style="width: 150px; height: 150px; object-fit: cover"
      />
      {% else %}
      <strong>{% trans "プロフィール画像がありません" %}</strong>
      {% endif %}
    </div>
  </div>

  <!-- パスワード -->
  <div class="row mt-4">
    <div class="col d-flex align-items-center">
      <h3 class="mr-2">{% trans "パスワード" %}</h3>
      <a href="{% url 'accounts:password_change' %}"
        ><i class="bi bi-pencil-square"></i
      ></a>
    </div>
  </div>
  <table class="table table-bordered">
    <tbody>
      <tr>
        <td style="width: 50%">{% trans "パスワード" %}</td>
        <td style="width: 50%">{% trans "非表示" %}</td>
      </tr>
    </tbody>
  </table>

  <!-- 権限 -->
  <div class="row mt-4">
    <div class="col"><h3>{% trans "権限" %}</h3></div>
  </div>
  <table class="table table-bordered">
    <tbody>
      {% if user.is_staff %}
      <tr>
        <td style="width: 50%">{% trans "スタッフ権限" %}</td>
        <td style="width: 50%">{% trans "あり" %}</td>
      </tr>
      {% else %}
      <tr>
        <td style="width: 50%">{% trans "スタッフ権限" %}</td>
        <td style="width: 50%">{% trans "なし" %}</td>
      </tr>
      {% endif %} {% if user.is_superuser %}
      <tr>
        <td>{% trans "スーパーユーザー権限" %}</td>
        <td>{% trans "あり" %}</td>
      </tr>
      {% else %}
      <tr>
        <td>{% trans "スーパーユーザー権限" %}</td>
        <td>{% trans "なし" %}</td>
      </tr>
      {% endif %}
    </tbody>
  </table>
  <hr />
  <div class="col"><h3>{% trans "フレンド情報" %}</h3></div>
  <div class="row">
    {% for friend in friends %}
      <div class="col-md-3 mb-4">
        <div class="card">
          <a href="{% url 'profile' friend.username %}" style="color: inherit;">
            <img class="card-img-top" src="{{ friend.avatar }}" alt="{{ friend.username }}">
            <div class="card-body">
              <h5 class="card-title font-weight-bold">@{{ friend.username }}</h5>
            </div>
          </a>
        </div>
      </div>
    {% empty %}
      <div class="col">
        <p>{% trans "フレンドはいません" %}</p>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

PongChat/accounts/templates/accounts/password_change_done.html
{% extends "common/base.html" %}
{% block content %}
{% load i18n %}
<div class="container">
  <div class="col-md-6 offset-md-3">
    <div class="card mt-3 mb-3 bg-light">
      <!-- カードヘッダー -->
      <div class="card-header bg-success text-light">
        <h4>Change Password Done</h4>
      </div>
      <!-- カードボディー -->
      <div class="card-body">
        <p>{% trans "パスワードを更新しました。" %}</p>
        <hr />
        <p><a href="{% url 'accounts:my_page' user.pk %}">{% trans "マイページ" %}</a></p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

PongChat/accounts/templates/accounts/signup_done.html
{% extends "common/base.html" %}
{% block title%} Signup Done {% endblock %}
{% block content %}
{% load i18n %}
<div class="container">
  <div class="col-md-6 offset-md-3">
    <div class="card mt-3 mb-3 bg-light">
      <!-- カードヘッダー -->
      <div class="card-header bg-success text-light">
        <h4>Sign up Done</h4>
      </div>
      <!-- カードボディー -->
      <div class="card-body">
        <p>{% trans "サインアップが完了しました" %}</p>
        <hr />
        <p>
          <a href="{% url 'accounts:login' %}">{% trans "ログイン" %}</a>
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

PongChat/accounts/templates/accounts/top.html
{% extends "common/base.html" %}
{% block content %}
{% load i18n %}
  <body>
    <section id="hero" class="py-5 bg-light container-fluid">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6">
            <p class="m-0 fw-bold text-primary">{% trans "PongChat" %}</p>
            <h1 class="mt-1 fw-bold">{% trans "42最終課題ft_transcendence" %}</h1>
            <p class="mt-3 fs-4">{% trans "PingPongゲームとチャットができます!" %}</p>
            {% if user.is_authenticated %}
              <a class="px-5 py-3 fw-bold rounded-0 btn btn-secondary disabled">{% trans "ログイン済み" %}</a>
            {% else %}
              <a class="px-5 py-3 fw-bold rounded-0 btn btn-primary" href="{% url 'accounts:login' %}">{% trans "ログイン/サインアップ" %}</a>
            {% endif %}
          </div>
          <div class="col-lg-6 d-none d-lg-block">
            <!-- ロゴとかなんか入れる用のところ  -->
            <!-- <img src="https://via.placeholder.com/500x400" alt="PongChat" class="img-fluid"> -->
          </div>
        </div>
      </div>
    </section>

    <section id="feature" class="py-5">
      <div class="container">
        <div class="row justify-content-center text-center">
          <div class="col-md-8">
            <p class="m-0 fw-bold text-primary">{% trans "SERVICE" %}</p>
            <h2 class="mt-2 mb-4 fw-bold">{% trans "サービス内容" %}</h2>
          </div>
        </div>
        <div class="row mt-5 justify-content-center align-items-center">
          <div class="col-md-4 mb-4">
            <a class="nav-link" href="{% url 'chat-home' %}">
              <div class="p-4 bg-white shadow-sm rounded">
                <i class="bi bi-chat-dots fs-1 text-primary"></i>
                <h5 class="mt-3 mb-0 fw-bold">{% trans "リアルタイムチャット" %}</h5>
                <p class="mt-3 mb-0 text-muted">{% trans "リアルタイムでのチャット機能があります!" %}</p>
              </div>
            </a>
          </div>
          <div class="col-md-4 mb-4">
            <a class="nav-link" href="{% url 'pingpong:index' %}">
              <div class="p-4 bg-white shadow-sm rounded">
                <i class="bi bi-controller fs-1 text-primary"></i>
                <h5 class="mt-3 mb-0 fw-bold">{% trans "ピンポンゲーム" %}</h5>
                <p class="mt-3 mb-0 text-muted">{% trans "ピンポンゲームができます。" %}</p>
              </div>
            </a>
          </div>
        </div>
      </div>
    </section>
    <section id="cta" class="py-5 bg-primary text-white">
      <div class="container d-flex flex-column gap-4 align-items-center">
        <h2 class="fw-bold">{% trans "ログインしてみる👀" %}</h2>
        {% if user.is_authenticated %}
          <a class="px-5 py-3 fw-bold rounded-0 btn btn-light disabled">{% trans "ログイン済み" %}</a>
        {% else %}
          <a class="px-5 py-3 fw-bold rounded-0 btn btn-light" href="{% url 'accounts:login' %}">{% trans "ログイン/サインアップ" %}</a>
        {% endif %}
      </div>
    </section>
  </body>
{% endblock %}

PongChat/accounts/templates/accounts/user_form.html
{% extends "common/base.html" %}
{% block title %}{{ process_name }} {% endblock %}
{% load static %}
{% block content %}
{% load i18n %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8">
      <div class="card mt-3 mb-3 bg-light">
        <div id="process-name" class="card-header bg-success text-light">
          <h4>{{ process_name }}</h4>
        </div>
        <div class="card-body">
          <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group p-2">
                <label for="{{ field.id_for_label }}"
                  >{{ field.label_tag }}{% if field.field.required %}<span
                    class="text-danger"
                    >*</span
                  >{% endif %}</label
                >
                {{ field }} {% if field.errors %}
                <div class="alert alert-danger mt-2" role="alert">
                  {% for error in field.errors %}
                  <div>{{ error }}</div>
                  {% endfor %}
                </div>
                {% endif %}
              </div>
            {% endfor %}
            {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {{ form.non_field_errors }}
            </div>
            {% endif %}
            <div class="form-group text-center">
              <img
                id="image-preview"
                src="#"
                alt="Profile Image Preview"
                class="rounded-circle border"
                style="
                  width: 200px;
                  height: 200px;
                  object-fit: cover;
                  display: none;
                "
              />
            </div>

            <div class="d-flex justify-content-between">
              {% if process_name == 'Sign Up'%}
              <a
                href="{% url 'accounts:top' %}"
                class="btn btn-outline-secondary btn-lg mt-4"
                >{% trans "キャンセル" %}</a
              >
              {% else %}
              <a
                href="{% url 'accounts:my_page' user.pk %}"
                class="btn btn-outline-secondary btn-lg mt-4"
                >{% trans "キャンセル" %}</a
              >
              {% endif %}
              <button type="submit" class="btn btn-success btn-lg mt-4">
                {{ process_name }}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="{% static 'accounts/scripts/preview_image.js' %}"></script>
{% endblock %}