PongChat/PongChat/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path("pingpong/", include("pingpong.urls")),
    path("", include("accounts.urls")),
    path("chat/", include("chat.urls")),
    path("prometheus/", include("django_prometheus.urls")),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PongChat/chat/urls.py
from django.urls import path

from .views import (
    chat_view,
    get_or_create_chatroom,
    profile_view,
    user_block_post,
    user_friend_post,
    user_list,
)

urlpatterns = [
    path("", user_list, name="chat-home"),
    path("<username>", get_or_create_chatroom, name="start-chat"),
    path("room/<chatroom_name>", chat_view, name="chatroom"),
    path("@<username>/", profile_view, name="profile"),
    path("block/<str:username>", user_block_post, name="block"),
    path("friend/<str:username>", user_friend_post, name="friend"),
]

PongChat/pingpong/urls.py
from django.urls import path

from . import views

app_name = "pingpong"

urlpatterns = [
    path("", views.index, name="index"),
    path("game_play", views.game_play, name="game_play"),
    path("home", views.home, name="home"),
    path("how_to_play", views.how_to_play, name="how_to_play"),
    path("multiplayer_lobby", views.multiplayer_lobby, name="multiplayer_lobby"),
    path("multiplayer_options", views.multiplayer_options, name="multiplayer_options"),
    path(
        "multiplayer_play_four",
        views.multiplayer_play_four,
        name="multiplayer_play_four",
    ),
    path(
        "multiplayer_play_local",
        views.multiplayer_play_local,
        name="multiplayer_play_local",
    ),
    path(
        "multiplayer_play_remote/<str:game_id>",
        views.multiplayer_play_remote,
        name="multiplayer_play_remote",
    ),
    path("single_play_setup", views.single_play_setup, name="single_play_setup"),
    path("single_play_start", views.single_play_start, name="single_play_start"),
    path("tournament_bracket", views.tournament_bracket, name="tournament_bracket"),
    path("tournament_finish", views.tournament_finish, name="tournament_finish"),
    path("tournament_play", views.tournament_play, name="tournament_play"),
    path(
        "tournament_registration",
        views.tournament_registration,
        name="tournament_registration",
    ),
    path(
        "tournament_winner_name_response/<int:round>",
        views.tournament_winner_name_response,
        name="tournament_winner_name_response",
    ),
]

PongChat/pingpong/models.py
from django.conf import settings
from django.db import models


class Game(models.Model):
    player1: models.ForeignKey = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="games_as_player1",
        null=True,
    )

    player2: models.ForeignKey = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="games_as_player2",
        null=True,
    )

    score1: models.IntegerField = models.IntegerField(default=0)
    score2: models.IntegerField = models.IntegerField(default=0)
    score_last_update: models.DateTimeField = models.DateTimeField(auto_now_add=True)

    status: models.CharField = models.CharField(
        max_length=10,
        choices=[("ongoing", "Ongoing"), ("done", "Done")],
        default="ongoing",
    )

    date_start: models.DateTimeField = models.DateTimeField(auto_now_add=True)
    date_end: models.DateTimeField = models.DateTimeField(null=True, blank=True)

    winner: models.ForeignKey = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="games_won",
        null=True,
        blank=True,
    )

    def __str__(self):
        return f"{self.id}: {self.player1} vs {self.player2}"


# guest_user
# - id
# - username

# TournamentMatch
# - id
# - tournament_id(tournament.id)
# - round
# - user1(gusest_user.id)
# - user2(guest_user_id)
# - winner(guest_user_id)

# tournament
# - id
# - partipants_amount
# - timestamp
# - winner(guest_user_id)


class GuestUser(models.Model):
    username: models.CharField = models.CharField(max_length=100)

    def __str__(self):
        return self.username


class Tournament(models.Model):
    participants_amount: models.IntegerField = models.IntegerField()
    timestamp: models.DateTimeField = models.DateTimeField(auto_now_add=True)
    winner: models.ForeignKey = models.ForeignKey(
        GuestUser,
        on_delete=models.CASCADE,
        related_name="tournaments_won",
        null=True,
        blank=True,
    )

    def __str__(self):
        return f"{self.id}: {self.participants_amount} participants"


class TournamentMatch(models.Model):
    tournament: models.ForeignKey = models.ForeignKey(
        Tournament,
        on_delete=models.CASCADE,
        related_name="results",
    )
    round: models.IntegerField = models.IntegerField()
    user1: models.ForeignKey = models.ForeignKey(
        GuestUser,
        on_delete=models.CASCADE,
        related_name="tournament_results_as_user1",
    )
    user2: models.ForeignKey = models.ForeignKey(
        GuestUser,
        on_delete=models.CASCADE,
        related_name="tournament_results_as_user2",
    )
    winner: models.ForeignKey = models.ForeignKey(
        GuestUser,
        on_delete=models.CASCADE,
        related_name="tournament_results_as_winner",
        null=True,
        blank=True,
    )

    def __str__(self):
        return f"tournament{self.tournament.id}:\
            {self.user1} vs {self.user2} in round {self.round}"

PongChat/pingpong/views.py
import json
import math

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

# from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import redirect, render

from .models import GuestUser, Tournament, TournamentMatch

# @login_required
# def index(request):
#     return render(request, "pingpong/index.html")


User = get_user_model()


# @login_required
def index(request):
    return render(request, "pingpong/home.html")


@login_required
def game_play(request):
    return render(request, "pingpong/game_play.html")


# @login_required
def home(request):
    return render(request, "pingpong/home.html")


# @login_required
def how_to_play(request):
    return render(request, "pingpong/how_to_play.html")


# @login_required
def multiplayer_play_local(request):
    return render(request, "pingpong/multiplayer_play_local.html")


# @login_required
def multiplayer_play_four(request):
    return render(request, "pingpong/multiplayer_play_four.html")


@login_required
def multiplayer_lobby(request):
    online_players = User.objects.filter(is_remote_multiplayer_active=True).exclude(
        id=request.user.id
    )
    return render(
        request, "pingpong/multiplayer_lobby.html", {"online_players": online_players}
    )


# @login_required
def multiplayer_options(request):
    return render(request, "pingpong/multiplayer_options.html")


@login_required
def multiplayer_play_remote(request, game_id):
    context = {"game_id": game_id}
    return render(request, "pingpong/multiplayer_play_remote.html", context)


# @login_required
def single_play_setup(request):
    if request.method == "POST":
        difficulty = request.POST.get("difficulty")
        return redirect("pingpong:game_play", difficulty=difficulty)
    return render(request, "pingpong/single_play_setup.html")


# @login_required
def single_play_start(request):
    difficulty = request.POST.get("difficulty")
    return render(
        request, "pingpong/single_play_start.html", {"difficulty": difficulty}
    )


def tournament_finish(request):
    tournament_id = request.session.get("tournament_id")
    tournament = Tournament.objects.get(id=tournament_id)
    match = TournamentMatch.objects.get(tournament_id=tournament_id, round=1)
    winner = match.winner
    tournament.winner = winner
    tournament.save()
    return render(
        request, "pingpong/tournament_finish.html", {"winner_name": winner.username}
    )


def tournament_play(request):
    if request.method == "POST":
        data = json.loads(request.body)
        match_id = request.session.get("match_id")
        winner_id = data.get("winner_id")
        match = TournamentMatch.objects.get(id=match_id)
        winner = GuestUser.objects.get(id=winner_id)
        match.winner = winner
        match.save()
        return redirect("pingpong:tournament_bracket")
    return render(
        request,
        "pingpong/tournament_play.html",
    )


# @login_required
def tournament_bracket(request):
    participants = request.session.get("participants")
    participant_names = request.session.get("participant_names")
    round = request.session.get("round")
    if request.method == "POST":
        tournament_id = request.session.get("tournament_id")
        matches = TournamentMatch.objects.filter(
            tournament_id=tournament_id, winner=None
        )
        if matches:
            match = matches.first()
            request.session["match_id"] = match.id
            request.session["user1_id"] = match.user1.id
            request.session["user2_id"] = match.user2.id
            request.session["user1_name"] = match.user1.username
            request.session["user2_name"] = match.user2.username
            return redirect("pingpong:tournament_play")
        else:
            matches = TournamentMatch.objects.filter(
                tournament_id=tournament_id, round=round
            )
            round -= 1
            request.session["round"] = round
            if round <= 0:
                return redirect("pingpong:tournament_finish")
            for i in range(2**round // 2):
                TournamentMatch.objects.create(
                    tournament=Tournament.objects.get(id=tournament_id),
                    round=round,
                    user1=matches[2 * i].winner,
                    user2=matches[2 * i + 1].winner,
                ).save()
            matches = TournamentMatch.objects.filter(
                tournament_id=tournament_id, winner=None
            )
            match = matches.first()
            request.session["match_id"] = match.id
            request.session["user1_id"] = match.user1.id
            request.session["user2_id"] = match.user2.id
            request.session["user1_name"] = match.user1.username
            request.session["user2_name"] = match.user2.username
            return redirect("pingpong:tournament_play")

    return render(
        request,
        "pingpong/tournament_bracket.html",
        {"participants": participants, "participant_names": participant_names},
    )


# @login_required
def tournament_registration(request):
    if request.method == "POST":
        participants = int(request.POST.get("participants"))
        if any(request.POST.get(f"name{i}") == "" for i in range(participants)):
            return render(request, "pingpong/tournament_registration.html")
        participant_names = [request.POST.get(f"name{i}") for i in range(participants)]

        guest_users = []
        for name in participant_names:
            guest_users.append(GuestUser.objects.create(username=name))

        tournament = Tournament.objects.create(participants_amount=participants)

        round = math.ceil(math.log2(participants))
        for i in range(participants // 2):
            TournamentMatch.objects.create(
                tournament=tournament,
                round=round,
                user1=guest_users[2 * i],
                user2=guest_users[2 * i + 1],
            ).save()

        request.session["participants"] = participants
        request.session["participant_names"] = participant_names
        request.session["tournament_id"] = tournament.id
        request.session["round"] = round

        return redirect("pingpong:tournament_bracket")

    return render(request, "pingpong/tournament_registration.html")


def tournament_winner_name_response(request, round):
    tournament_id = request.session.get("tournament_id")
    matches = TournamentMatch.objects.filter(
        tournament_id=tournament_id, round=round + 1, winner__isnull=False
    ).order_by("id")
    if matches:
        winner = []
        for match in matches:
            winner.append(match.winner.username)
        data = {
            "winner": winner,
        }
    else:
        matches = TournamentMatch.objects.filter(
            tournament_id=tournament_id, round=round
        ).order_by("id")
        participants = []
        for match in matches:
            participants.append(match.user1.username)
            participants.append(match.user2.username)
        data = {
            "winner": participants,
        }
    return JsonResponse(data)

PongChat/pingpong/templates/pingpong/home.html
{% extends "common/base.html" %}
{% load i18n %}
{% block content %}
<div class="container mt-5">
  <h1 class="display-4 text-center mb-4">{% trans "ようこそPing Pong Gameへ!" %}</h1>
  <p class="lead text-center mb-5">{% trans "ゲームモードを選んでね:" %}</p>
  <div class="d-flex justify-content-center align-items-center mb-5">
    <a href="{% url 'pingpong:single_play_setup' %}" class="btn btn-lg btn-primary mx-2">
      {% trans "一人で遊ぶ" %}
    </a>
    <a href="{% url 'pingpong:multiplayer_options' %}" class="btn btn-lg btn-success mx-2">
      {% trans "複数人と遊ぶ" %}
    </a>
    <a href="{% url 'pingpong:tournament_registration' %}" class="btn btn-lg btn-warning mx-2 async-link">
      {% trans "トーナメント" %}
    </a>
  </div>
  <div class="text-center mb-4">
    <h2 class="h5 mb-3">{% trans "遊び方を見る" %}</h2>
    <p class="mb-4">{% trans "ゲームのルールと操作方法に慣れて、プレイ体験を向上させましょう。" %}</p>
    <a href="{% url 'pingpong:how_to_play' %}" class="btn btn-lg btn-info">
      {% trans "遊び方" %}
    </a>
  </div>
</div>
{% endblock %}

PongChat/pingpong/templates/pingpong/how_to_play.html
{% extends "common/base.html" %}
{% load i18n %}

{% block content %}
<div class="container mt-5">
  <h1 class="display-4 text-center mb-4 ">{% trans "ピンポンゲームの遊び方" %}</h1>
  
  <div class="card mb-4 border-primary">
    <div class="card-header bg-primary text-white">
      <h2 class="card-title h5">{% trans "ゲームのルール" %}</h2>
    </div>
    <div class="card-body bg-light">
      <p class="card-text">{% trans "このゲームは11点先取で行われます。先に11点に到達したプレイヤーが試合に勝利します。" %}</p>
    </div>
  </div>

  <div class="card mb-4 border-success">
    <div class="card-header bg-success text-white">
      <h2 class="card-title h5">{% trans "ゲームモード" %}</h2>
    </div>
    <div class="card-body bg-light">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">{% trans "シングルプレイ：コンピュータと対戦します。" %}</li>
        <li class="list-group-item">{% trans "マルチプレイリモート：インターネット越しに他のプレイヤーと対戦します。" %}</li>
        <li class="list-group-item">{% trans "マルチプレイローカル：同じデバイスで他のプレイヤーと対戦します。" %}</li>
        <li class="list-group-item">{% trans "トーナメント：複数のプレイヤーとトーナメント形式で対戦します。" %}</li>
      </ul>
    </div>
  </div>

  <div class="card border-warning">
    <div class="card-header bg-warning">
      <h2 class="card-title h5 text-dark">{% trans "操作方法" %}</h2>
    </div>
    <div class="card-body bg-light">
      <p class="card-text">{% trans "シングルプレイモードでは、矢印キーを使ってパドルを動かします。" %}</p>
      <p class="card-text">{% trans "二人対戦の場合、一方のプレイヤーは「W」と「S」キーでパドルを上下に動かし、もう一方のプレイヤーは矢印キーを使用します。" %}</p>
    </div>
  </div>
</div>
{% endblock %}

PongChat/pingpong/templates/pingpong/multiplayer_lobby.html
{% extends 'common/base.html' %}
{% block title %}Multiplayer Lobby{% endblock%}
{% block content %}
<div class="container">
  <h1>Multiplayer lobby</h1>
  <p>Click the button below to find a match:</p>
  <button id="matchButton" class="btn btn-success">Find Match</button>
  <p id="statusMessage"></p>
  <a href="{% url 'pingpong:multiplayer_options' %}" class="btn btn-warning"
    >Exit</a
  >
</div>
<script>
  const button = document.querySelector("#matchButton");
  const statusMessage = document.querySelector("#statusMessage");

  button.addEventListener("click", function () {
    statusMessage.textContent = "Finding match...";
    button.disabled = true;

    const protocol = window.location.protocol === "https:" ? "wss:": "ws:";
    const host = window.location.host;
    const socket = new WebSocket(`${protocol}//{{ request.get_host }}/ws/game/`);

    socket.onopen = function (event) {
      socket.send(
        JSON.stringify({
          action: "start_match",
        }),
      );
    };

    socket.onmessage = function (event) {
      const data = JSON.parse(event.data);
      if (data.message === "match_found") {
        window.location.href = data.url;
      }
    };

    socket.onclose = function (event) {
      statusMessage.textContent = "";
      button.disabled = false;
    };

    socket.onerror = function (event) {
      statusMessage.textContent = "An error occurred. Please try again.";
      button.disabled = false;
    };
  });
</script>
{% endblock %}

PongChat/pingpong/templates/pingpong/multiplayer_options.html
{% extends 'common/base.html' %}
{% block title %}Multiplayer Options{% endblock %}
{% block content %}
<div class="container">
  <h1>Multiplayer Options</h1>
  <div class="game-options">
    <a href="{% url 'pingpong:multiplayer_lobby' %}" class="btn btn-primary async-link"
      >Remote Play</a
    >
    <a
      href="{% url 'pingpong:multiplayer_play_local' %}"
      class="btn btn-secondary async-link"
      >Local Play</a
    >
    <a
      href="{% url 'pingpong:multiplayer_play_four' %}"
      class="btn btn-success async-link"
      >Four People Play</a
    >
  </div>
</div>
{% endblock %}

PongChat/pingpong/templates/pingpong/multiplayer_play_four.html
{% extends "common/base.html" %}
{% block title %}Ping Pong Game{% endblock %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'pingpong/css/style.css' %}" />
{% endblock %}
{% block content %}
<div
  class="container fullscreen d-flex justify-content-center align-items-center"
>
  <canvas id="myCanvas"></canvas>
  <div
    id="game-over-message"
    class="text-center d-none position-absolute top-50 start-50 translate-middle"
  >
    <div class="alert alert-info rounded-pill shadow-lg p-4 fs-1" role="alert">
      <span id="gameOverText"></span>
    </div>
    <button
      id="restartButton"
      class="btn btn-primary btn-lg rounded-pill shadow-sm mt-3"
    >
      Restart
    </button>
    <a
      id="homeButton"
      href="{% url 'pingpong:home' %}"
      class="btn btn-secondary btn-lg rounded-pill shadow-sm mt-3"
      >Home</a
    >
  </div>
</div>
<script
  type="module"
  src="{% static 'pingpong/js/multiplay_four/main.js' %}"
></script>
{% endblock %}

PongChat/pingpong/templates/pingpong/multiplayer_play_local.html
{% extends "common/base.html" %}
{% block title %}Ping Pong Game{% endblock %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'pingpong/css/style.css' %}" />
{% endblock %}
{% block content %}
<div
  class="container fullscreen d-flex justify-content-center align-items-center"
>
  <canvas id="myCanvas"></canvas>
  <button id="speedToggle" class="btn btn-info btn-lg rounded-pill shadow-sm mt-3 position-absolute">Normal Speed</button>
  <div
    id="game-over-message"
    class="text-center d-none position-absolute top-50 start-50 translate-middle"
  >
    <div class="alert alert-info rounded-pill shadow-lg p-4 fs-1" role="alert">
      <span id="gameOverText"></span>
    </div>
    <button
      id="restartButton"
      class="btn btn-primary btn-lg rounded-pill shadow-sm mt-3"
    >
      Restart
    </button>
    <a
      id="homeButton"
      href="{% url 'pingpong:home' %}"
      class="btn btn-secondary btn-lg rounded-pill shadow-sm mt-3"
      >Home</a
    >
  </div>
</div>
<script
  type="module"
  src="{% static 'pingpong/js/multiplay_local/main.js' %}"
></script>
{% endblock %}

PongChat/pingpong/templates/pingpong/multiplayer_play_remote.html
{% extends "common/base.html" %}
{% block title %}Ping Pong Game{% endblock %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'pingpong/css/style.css' %}" />
{% endblock %}
{% block content %}
<div
  class="container fullscreen d-flex justify-content-center align-items-center"
>
  <canvas id="myCanvas"></canvas>
  <div
    id="game-over-message"
    class="text-center d-none position-absolute top-50 start-50 translate-middle"
  >
    <div class="alert alert-info rounded-pill shadow-lg p-4 fs-1" role="alert">
      <span id="gameOverText"></span>
    </div>
    <a
      id="restartButton"
      href="{% url 'pingpong:multiplayer_lobby' %}"
      class="btn btn-primary btn-lg rounded-pill shadow-sm mt-3 async-link"
    >
      Restart
  </a>
    <a
      id="homeButton"
      href="{% url 'pingpong:home' %}"
      class="btn btn-secondary btn-lg rounded-pill shadow-sm mt-3"
      >Home</a
    >
  </div>
</div>
<script type="module">
  import { initializeGame } from"{% static 'pingpong/js/multiplay_remote/main.js' %}";
  const gameId = "{{ game_id }}";
  initializeGame(gameId);
</script>
{% endblock %}

PongChat/pingpong/templates/pingpong/single_play_setup.html
{% extends 'common/base.html' %}
{% block content %}
<div class="container">
  <h1>single play setup</h1>
  <form action="{% url 'pingpong:single_play_start' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="difficulty">select difficulty:</label>
      <select id="difficulty" name="difficulty" class="form-control">
        <option value="easy">easy</option>
        <option value="medium">medium</option>
        <option value="hard">hard</option>
      </select>
    </div>
    <button type="submit" class="btn btn-primary">start game</button>
  </form>
</div>
{% endblock %}

PongChat/pingpong/templates/pingpong/single_play_start.html
{% extends "common/base.html" %}
{% block title %}Ping Pong Game{% endblock %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'pingpong/css/style.css' %}" />
{% endblock %}
{% block content %}
<div
  class="container fullscreen d-flex justify-content-center align-items-center"
>
  <canvas id="myCanvas"></canvas>
  <button id="speedToggle" class="btn btn-info btn-lg rounded-pill shadow-sm mt-3 position-absolute">Normal Speed</button>
  <div
    id="game-over-message"
    class="text-center d-none position-absolute top-50 start-50 translate-middle"
  >
    <div class="alert alert-info rounded-pill shadow-lg p-4 fs-1" role="alert">
      <span id="gameOverText"></span>
    </div>
    <button
      id="restartButton"
      class="btn btn-primary btn-lg rounded-pill shadow-sm mt-3"
    >
      Restart
    </button>
    <a
      id="homeButton"
      href="{% url 'pingpong:home' %}"
      class="btn btn-secondary btn-lg rounded-pill shadow-sm mt-3"
      >Home</a
    >
  </div>
</div>
<script
  type="module"
  src="{% static 'pingpong/js/single_play/main.js' %}"
></script>
{% endblock %}

PongChat/pingpong/templates/pingpong/start_single_play.html
{% extends "common/base.html" %}
{% block title %}Ping Pong Game{% endblock %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'pingpong/css/style.css' %}" />
{% endblock %}
{% block content %}
<div
  class="container fullscreen d-flex justify-content-center align-items-center"
>
  <canvas id="myCanvas"></canvas>
  <div
    id="game-over-message"
    class="text-center d-none position-absolute top-50 start-50 translate-middle"
  >
    <div class="alert alert-info rounded-pill shadow-lg p-4 fs-1" role="alert">
      <span id="gameOverText"></span>
    </div>
    <button
      id="restartButton"
      class="btn btn-primary btn-lg rounded-pill shadow-sm mt-3"
    >
      Restart
    </button>
    <a
      id="homeButton"
      href="{% url 'pingpong:home' %}"
      class="btn btn-secondary btn-lg rounded-pill shadow-sm mt-3"
      >Home</a
    >
  </div>
</div>
<script
  type="module"
  src="{% static 'pingpong/js/single_play/main.js' %}"
></script>
{% endblock %}

PongChat/pingpong/templates/pingpong/tournament_bracket.html
{% extends "common/base.html" %}
{% block content %}
<div class="container mt-5">
    <h1 class="mb-4 text-center">Tournament Bracket</h1>
    <form method="post" class="text-center mb-4">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary rounded-pill">Next Match Start</button>
    </form>
    <div class="d-flex justify-content-center">
        <canvas id="tournamentCanvas" width="800" height="600" style="border-radius: 15px; border:1px solid #ccc;"></canvas>
    </div>
</div>
<script>
document.addEventListener('DOMContentLoaded', function () {
    const canvas = document.getElementById('tournamentCanvas');
    const ctx = canvas.getContext('2d');

    const participants = {{ participants }};
    const names = {{ participant_names|safe }};

    drawBracket(ctx, participants, names);
});

async function fetchJson(url) {
    try {
        const response = await fetch(url);
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }
        return await response.json();
    } catch (error) {
        console.error('Error fetching JSON:', error);
    }
}

function drawBracket(ctx, participants, names) {
    const width = ctx.canvas.width;
    const height = ctx.canvas.height;
    const matchHeight = 50;
    const matchMargin = 20;
    const roundWidth = width / (Math.ceil(Math.log2(participants)) + 1);
    const totalRounds = Math.ceil(Math.log2(participants)) + 1;
    const cornerRadius = 10; // 角の丸みの半径を設定

    for (let round = 0 ; round < totalRounds; round++) {
        const numMatches = Math.pow(2, round);
        const yOffset = (height - (numMatches * (matchHeight + matchMargin) - matchMargin)) / 2;

        for (let match = 0; match < numMatches; match++) {
            const x = width - (round + 1) * roundWidth;
            const y = yOffset + match * (matchHeight + matchMargin);

            // 角の丸い矩形を描画
            drawRoundedRect(ctx, x, y, roundWidth - 20, matchHeight, cornerRadius);
            
            // Set text for the match
            ctx.fillStyle = '#ffffff'; // 文字色は白色に
            ctx.font = '24px Arial';
            fetchJson('/pingpong/tournament_winner_name_response/' + round).then(data => {
                if (names.length > match) {
                    if (data["winner"][match].length > 0) {
                        ctx.fillText(data["winner"][match], x + 10, y + 30);
                    } 
                }
            });
        }
    }
}

function drawRoundedRect(ctx, x, y, width, height, radius) {
    ctx.beginPath();
    ctx.moveTo(x + radius, y);
    ctx.lineTo(x + width - radius, y);
    ctx.quadraticCurveTo(x + width, y, x + width, y + radius);
    ctx.lineTo(x + width, y + height - radius);
    ctx.quadraticCurveTo(x + width, y + height, x + width - radius, y + height);
    ctx.lineTo(x + radius, y + height);
    ctx.quadraticCurveTo(x, y + height, x, y + height - radius);
    ctx.lineTo(x, y + radius);
    ctx.quadraticCurveTo(x, y, x + radius, y);
    ctx.closePath();

    ctx.fillStyle = 'rgb(0, 149, 221)'; // 内部の色を塗る
    ctx.fill();
    ctx.strokeStyle = '#ffffff';  // 枠線の色
    ctx.stroke();
}



</script>
{% endblock %}

PongChat/pingpong/templates/pingpong/tournament_finish.html
{% extends "common/base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1 class="display-4">Congratulations!</h1>
            <p class="lead">The tournament has come to an exciting conclusion.</p>
            <hr class="my-4">
            <h2 class="display-5">Winner: {{ winner_name }}</h2>
            <p class="lead">
                A huge congratulations to {{ winner_name }} for their outstanding performance and victory!
            </p>
            <a class="btn btn-primary btn-lg mt-3" href="{% url 'pingpong:home' %}" role="button">Back to Home</a>
        </div>
    </div>
</div>
{% endblock %}